### ISSUE TITLE
Error in save/load sessions

### ISSUE THREAD

**Issue by awelormro** [jedrzejboczar/possession.nvim#11]
Again, the close everything except the open buffer is happening, tried the solution shown in previous threads but it's not workig, running on Arch Linux with the nvim 0.7.2

**Comment by jedrzejboczar** [comment]
What do you mean by "the close everything except the open buffer is happening"? What commands are you running (`PossessionClose`?), what do you expect to happen vs what actually happens (close all buffers? close all execpt one buffer?). What is the error message that you see? Could you point to the threads where this problem was already discussed? Because I don't know what is the problem, so I don't know how to help.

**Comment by wsrast** [comment]
I can comment on this one. I'm seeing the same behavior. In LunarVim, I've installed Possession and all the commands are available, but running `:PossessionSave mySes` will close all tabs (buffers) other than the currently selected one, *then* save the session.

I can have a half dozen buffers open, see tabs for each, then run the save command and they all disappear save the active one.

**Comment by jedrzejboczar** [comment]
What config are you using? Is `PossesionSave` actually "closing all buffers other than the currently selected one" (which I understand as closing all splits/tabs)? Or is it closing all buffers that are not visible in any windows?

If you're using the default settings (so just `require('possession').setup()`) then `plugins.delete_hidden_buffers` is enabled and uses [default config](https://github.com/jedrzejboczar/possession.nvim/blob/bdb7a99c4180bd6a45da1165e51fc31948412241/lua/possession/config.lua#L49-L55) (also described in readme, but I cannot link to particular lines). So if you have `buffers` in `setssionoptions`, then `delete_hidden_buffers` will run on `before_save`. The rationale is that most users don't want to save tens of buffers that could have been opened by things like LSP, etc. But if you want to preserve all hidden buffers (hidden = not visible in any window), then you can disable this behaviour using:
```lua
require('possession').setup {
    plugins = {
        delete_hidden_buffers = false,
    },
}
```

**Comment by jedrzejboczar** [comment]
The code is doing [string.match](https://www.lua.org/manual/5.1/manual.html#pdf-string.match), so the code basically enables the `before_save` hook if `buffer` is in `sessionoptions`.

Your naming of tabs/buffers/windows seems a bit confusing to me. Are you using them in the "vim meaning"? Which means:
* buffer - can be thought of as "a file that has been opened", it's not a graphical element, you can use the command `:buffers` to see a list of open buffers
* window - part of screen that shows a buffer (a view of a buffer)
* tab - collection (layout) of windows, when you have multiple tabs open they are usually shown in top bar, unless you're using somehting like [bufferline.nvim](https://github.com/akinsho/bufferline.nvim) which will show a list of buffers (so list of open files)

Here is somewhat helpful image: https://i.loli.net/2020/04/11/LJ1uifs38d6gjVw.png
I was talking about buffers/tabs in the "vim meaning". But I think you might be using something like bufferline.nvim and you mean tabs=buffers? Note that I don't use bufferline (I prefer tabs in the vim sense, so as different "views"), so I might be missing something about how bufferline works.

Anyway I think that your problem is the same as in https://github.com/jedrzejboczar/possession.nvim/issues/13, so please check if `delete_hidden_buffers = false` helps.

**Comment by awelormro** [comment]
Solved in this very last commit
