### ISSUE TITLE
How to integrate with alpha.nvim?

### ISSUE THREAD

**Issue by fjchen7** [jedrzejboczar/possession.nvim#22]
Follow the [this guide](https://github.com/jedrzejboczar/possession.nvim#startup-screen) in README.md I fail to integrate with alpha. I am trying to show all my saved sessions in alpha page. Is there an example? Very thanks!

**Comment by jedrzejboczar** [comment]
Hi, I think [alpha-nvim](https://github.com/goolord/alpha-nvim) is to be considered more like a library for building startup screens. It is actually quite challenging to build something with it (if not using one of the provided themes). That's why I didn't initially include a full example. 

For a starting point you can try the following gist: https://gist.github.com/jedrzejboczar/618b531d1e0de6a956c66132287689aa. It uses some helpers copied from existing alpha-nvim themes and from my config. It creates a startup screen with your sessions, you can change the workspace definitions to suite your needs. You may also experiment with the layout, add some additional highlights in the `create_button` function, etc.

**Comment by fjchen7** [comment]
Thank you for response. I post my version here which may look more concise.

```lua
return {  -- lazy.nvim
  "goolord/alpha-nvim",
  event = "VimEnter",
  opts = function()
    local dashboard = require("alpha.themes.dashboard")
    dashboard.section.buttons.val = {
      dashboard.button("f", " " .. " Find Files", ":Telescope find_files<cr>"),
      dashboard.button("e", " " .. " New Files", ":ene <BAR> startinsert <CR>"),
      dashboard.button("o", " " .. " Recent Files", ":Telescope frecency <CR>"),
      dashboard.button("g", " " .. " Find Text", ":Telescope live_grep <CR>"),
      dashboard.button("c", " " .. " Nvim Config", [[<cmd>PossessionLoad config<CR>]]),
      dashboard.button("z", "鈴" .. " Lazy", ":Lazy<CR>"),
      dashboard.button("q", " " .. " Quit", ":qa<CR>"),
      (function()
        local group = { type = "group", opts = { spacing = 0 } }
        group.val = {
          {
            type = "text",
            val = "Sessions",
            opts = {
              position = "center"
            }
          }
        }
        local path = vim.fn.stdpath("data") .. "/possession"
        local files = vim.split(vim.fn.glob(path .. "/*.json"), "\n")
        for i, file in pairs(files) do
          local basename = vim.fs.basename(file):gsub("%.json", "")
          local button = dashboard.button(tostring(i), "勒 " .. basename, "<cmd>PossessionLoad " .. basename .. "<cr>")
          table.insert(group.val, button)
        end
        return group
      end)()
    }
    dashboard.opts.layout[1].val = 8
    return dashboard
  end,
  config = function(_, dashboard)
    require("alpha").setup(dashboard.opts)
  end,
}
```

<img width="543" alt="image" src="https://user-images.githubusercontent.com/10106636/216283462-1b3eaa30-4f1f-4d37-ab90-209adaa046d0.png">

**Comment by jedrzejboczar** [comment]
Thanks, your example is definitely more concise. I added a link to your example in the README. 

You could also try using `require('possession.query').as_list()` instead of manually globbing the JSON files - this will automatically respect your `session_dir` settings if you decide to change it in setup and will return a list with session objects so you can use e.g. the `.name` key. But of course your solution is ok and I don't plan any breaking changes regarding how/where the sessions are stored.

**Comment by detrohutt** [comment]
Here's a modified version that:
* Makes use of the `as_list()` function mentioned in the comment above
* Changes the "frecency" command (which wasn't working for me) to "oldfiles"
* Increases spacing of "Sesssions" section to match upper section
* Removes `dashboard.opts.layout[1].val = 8` which as far as I can tell just adds some top padding which I was ok losing to make more room for sessions with the increased spacing needs

```
return {  -- lazy.nvim
    "goolord/alpha-nvim",
    event = "VimEnter",
    opts = function()
        local dashboard = require("alpha.themes.dashboard")
        dashboard.section.buttons.val = {
            dashboard.button("f", " " .. " Find Files", ":Telescope find_files<CR>"),
            dashboard.button("e", " " .. " New Files", ":ene <BAR> startinsert<CR>"),
            dashboard.button("o", " " .. " Recent Files", ":Telescope oldfiles<CR>"),
            dashboard.button("g", " " .. " Find Text", ":Telescope live_grep<CR>"),
            dashboard.button("c", " " .. " Nvim Config", [[<cmd>PossessionLoad config<CR>]]),
            dashboard.button("z", "鈴" .. " Lazy", ":Lazy<CR>"),
            dashboard.button("q", " " .. " Quit", ":qa<CR>"),
            (function()
                local group = { type = "group", opts = { spacing = 1 } }
                group.val = {
                    {
                        type = "text",
                        val = "Sessions",
                        opts = {
                            position = "center"
                        }
                    }
                }
                for i, session in pairs(require('possession.query').as_list()) do
                    local button = dashboard.button(tostring(i), "勒 " .. session.name, "<cmd>PossessionLoad " .. session.name .. "<cr>")
                    table.insert(group.val, button)
                end
                return group
            end)(),
        }
        return dashboard
    end,
    config = function(_, dashboard)
        require("alpha").setup(dashboard.opts)
    end,
}
```
