### ISSUE TITLE
Autosave is not working

### ISSUE THREAD

**Issue by thatanjan** [jedrzejboczar/possession.nvim#38]
First of all, thank you for the plugin. 
I am trying to autosave the currently loaded session. For example, I have saved a session with buffer `a` and `b`. If I open another buffer, then the session doesn't save the buffer. I always have to manually run the save command. 

Here is the config: 
```lua
    use {
        "jedrzejboczar/possession.nvim",
        requires = { "nvim-lua/plenary.nvim" },
        config = function()
            require("possession").setup {
                autosave = {
                    current = true,
                },
                plugins = { delete_hidden_buffers = false },
            }
        end,
    }
```
Neovim version: NVIM v0.10.0-dev-533+g7e301ed5b
I have also tested that on a stable version. Same problem. 
Config repo: https://github.com/thatanjan/neovim-config

Thanks in advance

**Comment by jedrzejboczar** [comment]
Hi, I have tried this on my setup, but it seems to works fine. Have you loaded an existing session before trying to auto-save? In order for `current` session to be saved you must load a named session before, so that the plugin knows which session to save. 

For example: 
* open buffers A, B
* `:SSave mysession`
* open buffer C
* use `:quitall` (now session has been auto-saved)
* start Neovim again
* use `:SLoad mysession`
* you should see buffer C

For this behavior to work, you must have `autosave.current=true` and `autosave.on_quit=true` (this one is the default). You can also do the same, but instead of `:quitall` use `:SLoad anothersession`, which should also trigger auto-save (if `autosave.on_load=true` which is the default).

**Comment by jedrzejboczar** [comment]
Sorry for even later response.

I think that autosaving more often may cause unexpected problems, but if you want to give it a try you could add the following code to your config:
```lua
local events = {
    'CursorHold',
    -- 'BufWinEnter',
    -- 'BufWinLeave',
    -- 'WinNew',
    -- 'WinClosed',
    -- 'TabNew',
}

vim.api.nvim_create_autocmd(events, {
    group = vim.api.nvim_create_augroup('PossessionAutosave', { clear = true }),
    callback = function()
        local session = require('possession.session')
        if session.session_name then
            session.autosave()
        end
    end
})
```

This will save on the `CursorHold` event, but you may instead try to use the other events (commented out). If you encounter errors (e.g. because some before_save handler tries to remove some buffer, etc.) you could try to ignore errors by replacing `session.autosave()` with `pcall(session.autosave)`.
